version: '3'
services:
  lhc-new:
    container_name: lhc-new
    build: .
    ports:
      - "8002:80"
    restart: always
    networks:
      - lhc-new
    volumes:
      - ./html:/var/www/html
      - ./logs:/var/log/

networks:
  lhc-new:
    driver: bridge
